### ISSUE TITLE
Unable to update title details

### ISSUE THREAD

**Issue by ghost** [fastaddons/MovieMeter#7]
**Describe the bug**  
Title details are not updated, there are some details that were updated months ago that are still the same as they were before.

Example: https://www.imdb.com/title/tt15767342/

**Comment by fastaddons** [comment]
Hello,
What exactly is not updated?
Some data are cached for a short period of time, but the rest should be pretty recent.
This is what I see:
![image](https://user-images.githubusercontent.com/55486931/187849773-3f46607b-dff1-4c50-987b-2a3e3350d090.png)

**Comment by ghost** [comment]
> Hello, What exactly is not updated? Some data are cached for a short period of time, but the rest should be pretty recent. This is what I see: ![image](https://user-images.githubusercontent.com/55486931/187849773-3f46607b-dff1-4c50-987b-2a3e3350d090.png)

Read the actors' names in the Movie Meter summary and the full list on the IMDb page.

**Comment by fastaddons** [comment]
Oh, I see now.
Sadly, this is outside my reach right now as these data comes from "OMDb" service: http://www.omdbapi.com/
I think his service is updating this info only very slowly and probably with higher priority to more popular movies.

Then info about episodes is pulled from official TV Maze service so that should be as fresh as possible.
And for the rating info I've build a custom script that updates it every day.

**Comment by ghost** [comment]
> Oh, I see now. Sadly, this is outside my reach right now as these data comes from "OMDb" service: http://www.omdbapi.com/ I think his service is updating this info only very slowly and probably with higher priority to more popular movies.
> 
> Then info about episodes is pulled from official TV Maze service so that should be as fresh as possible. And for the rating info I've build a custom script that updates it every day.

Okay, thanks for the info.
